@startuml

!include <tupadr3/common>
!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!includeurl ICONURL/Concepts/documents.puml
!includeurl ICONURL/Concepts/document.puml
!includeurl ICONURL/Concepts/application_generic.puml
!includeurl ICONURL/Concepts/folders.puml

[Web GIS] as wgc

package Datenbezug{
    [<$application_generic> Datenbezug] as db
    OFF_DOCUMENT(cat, catalog.json)

    db -right-> cat
}


package "Dateiablage"{
    [<$folders> HTTPs Directory] as http
    OFF_DOCUMENT(ilicat, ilidata.xtf)
}

[API - WMS oder WMTS] as wms

wgc --> db : URL open
db --> http
db --> wms



@enduml