@startuml

!include <tupadr3/common>
!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!includeurl ICONURL/Concepts/documents.puml
!includeurl ICONURL/Concepts/document.puml
!includeurl ICONURL/Concepts/application_generic.puml
!includeurl ICONURL/Concepts/folders.puml

package Config-Pipeline{
    [sql2json] as sj
    [json2ili] as ji
}

database "Meta-DB" {
    [tables] as tbl
}

package Datenbezug{
    OFF_DOCUMENT(cat, catalog.json)
}

package "Dateiablage"{
    OFF_DOCUMENT(ilicat, ilidata.xtf)
}

package "GRETL"{
    OFF_DOCUMENT(conf, conf.json)
}

sj --> tbl
sj --> conf
sj --> cat

ji--> cat
ji --> ilicat



@enduml