
@startuml

!include <tupadr3/common>
!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!includeurl ICONURL/Concepts/document.puml
!includeurl ICONURL/Concepts/documents.puml


package "Datenquellen"{
    database "GeoDB" {
        [ili2pg - Schema] as db
    }
    folder "INTERLIS Daten" {
        OFF_DOCUMENT(tf, "*.xtf, *.itf")
    }
}

node "SIMI"{
    
    component "SIMI (Web-App)" as simi {
      [metaBean2File]
    }
    () papi as "Für Publisher"
    simi - papi
    
    database "Meta-DB" as mdb {
        [Tables / Views] as mtrel
    }
    
    simi --> mdb
}

node "Pipeline (Jenkins)" as dag {

    component "Meta-Exporter" as mex {
      [metaBean2File ]
    }
}


[GDI WMTS] as wmts

package "Links" as link {
    [GDI WMS] as wms
    [GDI WGC] as wgc
    [geodienste] as ai
}


package "Datenbezug"{

		package "Portale (opendata, geocat)" {
			OFF_DOCUMENTS(isoCH, ISO-CH Metadaten (*.xml))
			[geocat] as gc
			[opendata.swiss] as od
		}

    node "Publisher (GRETL)" {
        [Publisher] as pub
    }
    
    node "Datenablage (AIO)"{
        OFF_DOCUMENTS(data, Daten-Dateien)
    }
    
    node "Datensuche" {
        [Datensuche] as ds
        OFF_DOCUMENTS(bconf, Konf-Dateien (*.*))
    }
    
    pub --> data : sftp (schreibend)
    ds --> data : https
    note on link
      - Daten-Zips
      - detailbeschreibung.html
    end note
}

package "Generische Clients"{
    [Browser] as httpc
    [FTP-Client] as ftpc
    
    httpc -[hidden]-> ftpc
}

package "Datenadministration"{
    [FTP-Client] as ftpadmin
}

pub -up-> db : DB Verbindung
pub -up-> tf : filesys read
pub -up-> papi : OAuth2

httpc --> data : https
ftpc  -left-> data : sftp (lesend)
ftpadmin  -up-> data : sftp (schreibend)


mex -up-> mtrel : DB Verbindung
mex --> isoCH : sftp
mex --> bconf : In Image brennen

od --> ds : HTTP Link
gc --> ds : HTTP Link

ds ---> wmts : Hintergrundkarte
ds ---> link : Themen-Links

@enduml