@startuml

!include <tupadr3/common>
!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!includeurl ICONURL/Concepts/document.puml
!includeurl ICONURL/Concepts/documents.puml


package "Datenquellen"{
    database "GeoDB" {
        [ili2pg - Schema] as db
    }
    folder "INTERLIS Daten" {
        OFF_DOCUMENT(tf, "*.xtf, *.itf")
    }
}

package "SIMI"{
    
    [SIMI] as simi
    () papi as "Für Publisher"
    () sapi as "Für Datensuche"
    papi - simi
    sapi - simi
    
    database "Meta-DB" as mdb {
        [Meta-Tables] as mtbl
        [Meta-Views] as mv
        note right of mv
        **theme_v:** Datenbereitstellung
        **themeitem_v:** Tabelle, Geotif, ...
        **attribute_v:** Attributeigenschaften
        end note
        
        mv --> mtbl
    }
    
    package "Nightly-Job. GRETL?" as nightly {
        [GM03-Exporter] as mex
    }
    
    simi --> mdb
    
    mex -up-> mv
    mex .up.> simi : POJO
    note on link
      Nur falls direkt auf
      POJO zugegriffen wird.
    end note
}

[GDI WMTS] as wmts

package "Links" as link {
    [GDI WMS] as wms
    [GDI WGC] as wgc
    [geodienste] as ai
}


package "Datenbezug"{

		package "Portale (opendata, geocat)" {
			OFF_DOCUMENT(gm03, gm03.xtf)
			[geocat] as gc
			[opendata.swiss] as od
		}

    package "Publisher (GRETL)" {
        [Publisher] as pub
    }
    
    package "Datenablage"{
        OFF_DOCUMENTS(data, Daten-Dateien)
    }
    
    package "Datensuche" {
        [Datensuche] as ds
        OFF_DOCUMENT(bconf, config.yaml)
        OFF_DOCUMENTS(regions, regions.json)
    }
    
    pub --> data : sftp (schreibend)
    ds --> data : https
    note on link
      - Daten-Zips
      - detailbeschreibung.html
    end note
}

package "Generische Clients"{
    [Browser] as httpc
    [FTP-Client] as ftpc
    
    httpc -[hidden]-> ftpc
}

package "Datenadministration"{
    [FTP-Client] as ftpadmin
}

pub -up-> db : db con
pub -up-> tf : filesys read
pub -up-> papi : OAuth2

httpc --> data : https
ftpc  -left-> data : ftp (lesend)
ftpadmin  -up-> data : sftp (schreibend)


note on link
  regions.json ist ein keyval json.
  -key: region layer identifier
  -val: layer als geojson
end note

mex --> gm03

od --> ds
gc --> ds

ds ---> wmts : Hintergrundkarte
ds ---> link : Themen-Links

ds -up-> sapi : Auth?

@enduml