@startuml
!include <tupadr3/common>
!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!includeurl ICONURL/Concepts/document.puml
!includeurl ICONURL/Concepts/documents.puml


package "Datenquelle des Themas"{
    database "GeoDB" {
        [ili2pg - Schema] as db
    }

    folder "Lokaler Ordner" {
        OFF_DOCUMENT(input_tf, *.xtf / *.itf)
    }
    
    db --> input_tf : "Preprocessing, falls Quelle = DB"
}

package "GRADLE - Build" {
    [publisher] as pub
}

folder "Publiziertes Thema, Ordner /aktuell" as aktuell{
    OFF_DOCUMENT(tf, *.xtf.zip / *.itf.zip)
    
    package "Falls aus Pub-Modell zusätzlich:"{
        OFF_DOCUMENT(gp, *.gpkg.zip)
        OFF_DOCUMENTS(shp, *.shp.zip)
        OFF_DOCUMENTS(dxf, *.dxf.zip)

        gp -[hidden]right-> shp
        shp -[hidden]right-> dxf
    }
}

input_tf --> pub
pub --> aktuell

legend
    Nicht abgebildet:
    - Umgang mit Regionen (Bei AV: Gemeindeeinteilung)
    - Archiv / Archivierung
end legend
@enduml