@startuml

!include <tupadr3/common>
!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!includeurl ICONURL/Concepts/document.puml
!includeurl ICONURL/Concepts/documents.puml
!includeurl ICONURL/Concepts/folder.puml
!includeurl ICONURL/Databases/database_partition_5.puml


database "Pub-DB" as pub{
    package "ili2pg - Schema AV" as schema {
        OFF_DATABASE_PARTITION_5(ds2401, DS 2401)
        OFF_DATABASE_PARTITION_5(ds2406, DS 2406)
    }
}

package "/tmp/pending" as pending {
    OFF_DOCUMENT(2401, 2401.itf)
    OFF_DOCUMENT(2406, 2406.itf)
}

package "tmp/stage/ch.so.agi.av" as stage {
    OFF_DOCUMENTS(dm01, ./ch.so.agi.av.dm01_so)
    OFF_DOCUMENTS(mop, ./ch.so.agi.av.mopublic)
}

pending --> dm01 : Pub 1. Zu verarbeitende Regionen auslesen / itf kopieren
pub --> mop : Pub 2. Regionen aus DB exportieren

pending -[hidden]right-> pub

legend
Nicht abgebildet:
- Ablage der itf im Ordner "pending" durch den GRETL-Job
- Hochladen via sftp und Verschmelzen mit den unveränderten Regionen
- Archivierung
end legend

@enduml